# Generated by Django 6.0.7 on 2026-07-11 09:42

import django.db.models.deletion
import django_accounting.mixins
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_ar', '0001_initial'),
        ('accounting_core', '0001_initial'),
        ('accounting_inventory', '0001_initial'),
        ('accounting_ledger', '0001_initial'),
        ('accounting_tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default=django_accounting.mixins.CurrencyMixin._default_currency, max_length=3)),
                ('bill_number', models.CharField(max_length=30)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('vendor_reference', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='accounting_ledger.journalentry')),
            ],
            options={
                'db_table': 'accounting_bill',
                'ordering': ['-bill_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('discount_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='accounting_inventory.itembatch')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting_ap.bill')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='accounting_inventory.item')),
                ('tax_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='accounting_tax.taxgroup')),
            ],
            options={
                'db_table': 'accounting_bill_line',
                'ordering': ['line_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_vendors', to='accounting_core.account')),
            ],
            options={
                'db_table': 'accounting_vendor',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting_ap.vendor'),
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='accounting_ap.bill')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_allocations', to='accounting_ar.payment')),
            ],
            options={
                'db_table': 'accounting_bill_payment',
                'abstract': False,
                'unique_together': {('bill', 'payment')},
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_85fc46_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='accounting__status_512f87_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['due_date'], name='accounting__due_dat_ce5e27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('vendor', 'bill_number')},
        ),
    ]
