# Generated by Django 6.0.7 on 2026-07-11 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_core', '0001_initial'),
        ('accounting_ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'accounting_tax_group',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=200)),
                ('tax_payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_payable_authorities', to='accounting_core.account')),
                ('tax_receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_receivable_authorities', to='accounting_core.account')),
            ],
            options={
                'verbose_name_plural': 'tax authorities',
                'db_table': 'accounting_tax_authority',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('rate_pct', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT / GST'), ('sales_tax', 'Sales Tax'), ('withholding', 'Withholding Tax'), ('excise', 'Excise Tax'), ('other', 'Other')], max_length=20)),
                ('is_compound', models.BooleanField(default=False)),
                ('is_inclusive', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('tax_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='accounting_tax.taxauthority')),
            ],
            options={
                'db_table': 'accounting_tax_rate',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('invoice_line', 'Invoice Line'), ('bill_line', 'Bill Line')], max_length=30)),
                ('source_id', models.UUIDField()),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_inclusive', models.BooleanField(default=False)),
                ('journal_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_line', to='accounting_ledger.journalline')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_lines', to='accounting_tax.taxrate')),
            ],
            options={
                'db_table': 'accounting_tax_line',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxGroupRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apply_order', models.PositiveIntegerField(default=1)),
                ('tax_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rates', to='accounting_tax.taxgroup')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='accounting_tax.taxrate')),
            ],
            options={
                'db_table': 'accounting_tax_group_rate',
                'ordering': ['apply_order'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_5a9026_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['effective_from', 'effective_to'], name='accounting__effecti_25bfd3_idx'),
        ),
        migrations.AddIndex(
            model_name='taxline',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__0bcc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxline',
            index=models.Index(fields=['tax_rate'], name='accounting__tax_rat_11aa35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxgrouprate',
            unique_together={('tax_group', 'tax_rate')},
        ),
    ]
