# Generated by Django 6.0.7 on 2026-07-11 09:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_core', '0001_initial'),
        ('accounting_ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'accounting_warehouse',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('non_stock', 'Non-stock')], default='product', max_length=20)),
                ('unit_of_measure', models.CharField(choices=[('pcs', 'Piece'), ('box', 'Box'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('m', 'Meter'), ('pack', 'Pack'), ('vial', 'Vial'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('other', 'Other')], default='pcs', max_length=20)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('reorder_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('is_expirable', models.BooleanField(default=False)),
                ('is_batch_tracked', models.BooleanField(default=False)),
                ('cogs_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cogs_items', to='accounting_core.account')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='accounting_core.account')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_items', to='accounting_core.account')),
            ],
            options={
                'db_table': 'accounting_item',
                'ordering': ['sku'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('storage_conditions', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('quarantine', 'Quarantine'), ('expired', 'Expired'), ('consumed', 'Fully Consumed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='accounting_inventory.item')),
            ],
            options={
                'db_table': 'accounting_item_batch',
                'ordering': ['expiration_date', 'batch_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cogs_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cogs_categories', to='accounting_core.account')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_categories', to='accounting_core.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting_inventory.itemcategory')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_categories', to='accounting_core.account')),
            ],
            options={
                'verbose_name_plural': 'item categories',
                'db_table': 'accounting_item_category',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='accounting_inventory.itemcategory'),
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aisle', models.CharField(blank=True, max_length=20)),
                ('rack', models.CharField(blank=True, max_length=20)),
                ('bin', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='accounting_inventory.warehouse')),
            ],
            options={
                'db_table': 'accounting_warehouse_location',
                'ordering': ['warehouse', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Purchase Receipt'), ('issue', 'Issue / Sale'), ('transfer', 'Internal Transfer'), ('adjustment', 'Stock Adjustment'), ('return_in', 'Customer Return'), ('return_out', 'Vendor Return'), ('opening', 'Opening Balance')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('movement_date', models.DateField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='accounting_ledger.journalentry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='accounting_inventory.item')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='accounting_inventory.itembatch')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_movements', to='accounting_inventory.warehouselocation')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_movements', to='accounting_inventory.warehouselocation')),
            ],
            options={
                'db_table': 'accounting_inventory_movement',
                'ordering': ['-movement_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('qty_reserved', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='accounting_inventory.item')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='accounting_inventory.itembatch')),
                ('warehouse_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='accounting_inventory.warehouselocation')),
            ],
            options={
                'db_table': 'accounting_inventory_balance',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['expiration_date'], name='accounting__expirat_992820_idx'),
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['status'], name='accounting__status_f2f579_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itembatch',
            unique_together={('item', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_type'], name='accounting__item_ty_bf0543_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_7a5f8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouselocation',
            unique_together={('warehouse', 'label')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type'], name='accounting__movemen_fb6754_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_date'], name='accounting__movemen_5d778e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['item', 'batch'], name='accounting__item_id_2f5cf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybalance',
            unique_together={('item', 'batch', 'warehouse_location')},
        ),
    ]
